import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/landing.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.hero}>
          <div>
            <p>WELCOME TO</p>
            <h1>ALASKA 13</h1>
            <pre>The thirteenth alumnus of <a href='http://www.smpistiqomahsambaspbg.sch.id/' target='_blank' rel='noreferrer nofollow'>Istiqomah Sambas Middle School</a></pre>
          </div>
          <div>
            <p>Some Images n' stuff</p>
          </div>
        </div>
        <div>
          <div>
            <p>a</p>
          </div>
        </div>
      </main>
    </div>
  )
}
